**Часть 1: «Следствие ведёт детектив»**

- [ ] Возьмите датасет из задания №1 [Модуль 1. **Введение в сбор данных**](https://www.notion.so/1-341985de290d4c1280ba3856ac98925f?pvs=21)
- [ ] Проанализируйте пропуски: определите их процент и расположение (случайны ли пропуски или есть закономерность?)
- [ ] Сформулируйте гипотезу о возможных причинах появления пропусков.
- [ ] Проанализируйте датасет на выбросы удобным вам методом.

---

**Часть 2: «Выбор подходящего оружия»**

- [ ]  Примените несколько разных методов работы с пропусками, выбросами.
- [ ]  Приведите данные в единый вид, поработайте над категориальными признаками.
- [ ]  Оцените, как каждый из методов повлиял на распределение данных и результаты простого анализа (например, расчёт среднего или простая регрессия).

---

**Часть 3: «Раскрытие дела»**

- [ ]  Выберите и обоснуйте самый эффективный метод для вашего набора данных.
- [ ]  Сформулируйте краткую рекомендацию по оптимальному подходу к обработке пропущенных значений в вашем датасете.

- [ ] 🏆 **Дополнительные баллы** («Расследование с изюминкой»):

      *+3 балла* Предложите собственный метод или комбинацию методов, которые лучше всего подходят именно для вашего случая.

In [8]:
from pathlib import Path
import os

import pandas as pd
from razdel import tokenize
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import zscore

#  Это позволяет отображать все строки в датасете
pd.set_option('display.max_rows', None)

In [3]:
RAW_PATH = Path(r"..\data\raw").as_posix()
PROCESSED_PATH = Path(r"..\data\processed").as_posix()
INTERIM_PATH = Path(r"..\data\interim").as_posix()
EXTERNAL_PATH = Path(r"..\data\external").as_posix()

assert (
    os.path.isdir(RAW_PATH)
    and os.path.isdir(PROCESSED_PATH)
    and os.path.isdir(INTERIM_PATH)
    and os.path.isdir(EXTERNAL_PATH)
)

# Часть 1

## Подгрузим датасет из задания №1

In [4]:
# Загрузим датасет из csv

news_df = pd.read_csv(Path(RAW_PATH / Path("news.csv")))
news_df.tail()

                                                   text        date
1885  Путин согласился с предложением Трампа, чтобы ...  2025-03-18
1886  Совет директоров ПАО «Интер РАО» рекомендовал ...  2025-03-18
1887  Телефонный разговор Путина и Трампа завершился...  2025-03-18
1888  В последние годы ESG перестал быть просто модн...  2025-03-18
1889  Google подписала «окончательное соглашение» о ...  2025-03-18

In [9]:
# Проверим наличие пропущенных значений (NaN) в датасете

news_df[news_df.isnull().any(axis=1)]

     text        date
1124  NaN  2025-04-04
1125  NaN  2025-04-04
1126  NaN  2025-04-04
1165  NaN  2025-04-03
1166  NaN  2025-04-03
1167  NaN  2025-04-03
1168  NaN  2025-04-03
1169  NaN  2025-04-03
1197  NaN  2025-04-03
1198  NaN  2025-04-03
1238  NaN  2025-04-02
1239  NaN  2025-04-02
1240  NaN  2025-04-02
1241  NaN  2025-04-02
1242  NaN  2025-04-02
1289  NaN  2025-04-01
1290  NaN  2025-04-01
1291  NaN  2025-04-01
1292  NaN  2025-04-01
1293  NaN  2025-04-01
1356  NaN  2025-03-31
1357  NaN  2025-03-31
1358  NaN  2025-03-31
1359  NaN  2025-03-31
1360  NaN  2025-03-31
1371  NaN  2025-03-31
1372  NaN  2025-03-31
1373  NaN  2025-03-31
1374  NaN  2025-03-31
1453  NaN  2025-03-28
1454  NaN  2025-03-28
1463  NaN  2025-03-28
1464  NaN  2025-03-28
1465  NaN  2025-03-28
1466  NaN  2025-03-28
1467  NaN  2025-03-28
1531  NaN  2025-03-26
1532  NaN  2025-03-26
1533  NaN  2025-03-26
1534  NaN  2025-03-26
1535  NaN  2025-03-26
1581  NaN  2025-03-25
1582  NaN  2025-03-25
1583  NaN  2025-03-25
1584  NaN  2025-03-25
1585  NaN  2025-03-25
1637  NaN  2025-03-24
1638  NaN  2025-03-24
1639  NaN  2025-03-24
1640  NaN  2025-03-24
1641  NaN  2025-03-24
1650  NaN  2025-03-24
1651  NaN  2025-03-24
1724  NaN  2025-03-21
1725  NaN  2025-03-21
1726  NaN  2025-03-21
1727  NaN  2025-03-21
1728  NaN  2025-03-21
1729  NaN  2025-03-21
1730  NaN  2025-03-21
1731  NaN  2025-03-21
1732  NaN  2025-03-21
1750  NaN  2025-03-21
1826  NaN  2025-03-19
1827  NaN  2025-03-19
1828  NaN  2025-03-19
1829  NaN  2025-03-19
1830  NaN  2025-03-19
1849  NaN  2025-03-19
1850  NaN  2025-03-19
1851  NaN  2025-03-19
1852  NaN  2025-03-19
1853  NaN  2025-03-19

**Необходимо узнать время поста чтобы найти него в группе и сделать предположения почему текст отсутствует**

In [ ]:
forbes_df = pd.read_csv(
    Path(RAW_PATH / Path("forbes-news.csv")), usecols=["date", "text"]
)

# Проверим наличие пропущенных значений (NaN) в датасете

forbes_df['date'] = pd.to_datetime(forbes_df['date'])

# Предварительно сгруппируем по дате т.к. в датасете есть дубли
sorted_forbes_df_with_nulls = forbes_df[forbes_df.isnull().any(axis=1)].groupby('date').first().reset_index()
sorted_forbes_df_with_nulls

In [23]:
# Добавим столбец с описанием отсутствия поста
sorted_forbes_df_with_nulls["description"] = ""

In [35]:
sorted_forbes_df_with_nulls.loc[0, ("description")] = "Поста не существет, возможно он был удален"    
sorted_forbes_df_with_nulls.loc[1, ("description")] = "Поста не существет, возможно он был удален"
sorted_forbes_df_with_nulls.loc[2, ("description")] = "Поста не существет, возможно он был удален"
sorted_forbes_df_with_nulls.loc[3, ("description")] = "Поста не существет, возможно он был удален"
sorted_forbes_df_with_nulls.loc[4, ("description")] = "Поста не существет, возможно он был удален"
sorted_forbes_df_with_nulls.loc[5, ("description")] = "Поста не существет, возможно он был удален"
sorted_forbes_df_with_nulls.loc[6, ("description")] = "Поста не существет, возможно он был удален"
sorted_forbes_df_with_nulls.loc[7, ("description")] = "Поста не существет, возможно он был удален"
sorted_forbes_df_with_nulls.loc[8, ("description")] = "Поста не существет, возможно он был удален"
sorted_forbes_df_with_nulls.loc[9, ("description")] = "Поста не существет, возможно он был удален"
sorted_forbes_df_with_nulls.loc[10, ("description")] = "Поста не существет, возможно он был удален"
sorted_forbes_df_with_nulls.loc[11, ("description")] = "Поста не существет, возможно он был удален"
sorted_forbes_df_with_nulls.loc[12, ("description")] = "Поста не существет, возможно он был удален"
sorted_forbes_df_with_nulls.loc[13, ("description")] = "Поста не существет, возможно он был удален"
sorted_forbes_df_with_nulls.loc[14, ("description")] = "Поста не существет, возможно он был удален"
sorted_forbes_df_with_nulls.loc[15, ("description")] = "Поста не существет, возможно он был удален"
sorted_forbes_df_with_nulls.loc[16, ("description")] = "Поста не существет, возможно он был удален"
sorted_forbes_df_with_nulls.loc[17, ("description")] = "Поста не существет, возможно он был удален"
sorted_forbes_df_with_nulls.loc[18, ("description")] = "Поста не существет, возможно он был удален"

In [36]:
sorted_forbes_df_with_nulls

                        date  text                                 description
0  2025-03-19 16:34:37+00:00  None  Поста не существет, возможно он был удален
1  2025-03-21 12:08:28+00:00  None  Поста не существет, возможно он был удален
2  2025-03-21 16:41:09+00:00  None  Поста не существет, возможно он был удален
3  2025-03-24 14:52:34+00:00  None  Поста не существет, возможно он был удален
4  2025-03-24 16:37:54+00:00  None  Поста не существет, возможно он был удален
5  2025-03-25 16:39:05+00:00  None  Поста не существет, возможно он был удален
6  2025-03-26 17:46:28+00:00  None  Поста не существет, возможно он был удален
7  2025-03-28 10:33:44+00:00  None  Поста не существет, возможно он был удален
8  2025-03-28 12:51:49+00:00  None  Поста не существет, возможно он был удален
9  2025-03-31 12:32:55+00:00  None  Поста не существет, возможно он был удален
10 2025-03-31 12:32:56+00:00  None  Поста не существет, возможно он был удален
11 2025-03-31 14:39:25+00:00  None  Поста не существет, возможно он был удален
12 2025-04-01 16:37:17+00:00  None  Поста не существет, возможно он был удален
13 2025-04-02 12:35:17+00:00  None  Поста не существет, возможно он был удален
14 2025-04-03 09:00:06+00:00  None  Поста не существет, возможно он был удален
15 2025-04-03 16:36:49+00:00  None  Поста не существет, возможно он был удален
16 2025-04-04 11:26:16+00:00  None  Поста не существет, возможно он был удален
17 2025-04-08 15:37:07+00:00  None  Поста не существет, возможно он был удален
18 2025-04-09 09:04:27+00:00  None  Поста не существет, возможно он был удален

In [15]:
forbes_df[forbes_df.isnull().any(axis=1)].shape

(72, 2)

**Была попытка найти каждый пост по дате и времени с целью понять почему текст отсутствует. Но найти закономерность не удалось. Посты просто не существуют**